### ISSUE TITLE
Using async functions may cause panics and segfaults

### ISSUE THREAD

**Issue by MaxVerevkin** [khvzak/mlua#104] opened 2021-11-28 12:01 UTC
```rust
use mlua::prelude::*;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let lua = Lua::new().into_static();

    lua.globals().set(
        "my_timer",
        lua.create_async_function(|_, (i, f): (u64, LuaFunction)| async move {
            tokio::task::spawn_local(async move {
                let dur = std::time::Duration::from_millis(i);
                loop {
                    let f = f.clone();
                    tokio::task::spawn_local(f.call_async::<(), ()>(()));
                    tokio::time::sleep(dur).await;
                }
            });
            Ok(())
        })?,
    )?;

    let local_set = tokio::task::LocalSet::new();
    local_set
        .run_until(
            lua.load(
                r#"
cnt = 0
my_timer(10, function()
    cnt = cnt + 1
    print(cnt)
end)
"#,
            )
            .exec_async(),
        )
        .await?;
    local_set.await;

    Ok(())
}
```
```text
❯ RUST_BACKTRACE=full cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/lua-test`
1
2
<...>
42
43
thread 'main' panicked at 'assertion failed: curr.is_running()', /home/maxv/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/state.rs:152:13
stack backtrace:
zsh: segmentation fault (core dumped)  RUST_BACKTRACE=full cargo r
```

What's interesting, is that it always counts to _about_ 43. Doesn't matter if I change the interval.

I'm not sure if this is a bug in `mlua` or `tokio`. Or perhaps I'm using `mlua` the wrong way.

**Comment by MaxVerevkin** [comment] 2021-11-28 14:54
I had
```toml
features = ["lua53", "async"]
```
If I change the features to
```toml
features = ["lua54", "vendored", "async"]
```
I get
```text
❯ RUST_BACKTRACE=full cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/lua-test`
1
2
<...>
26
27
lua-test: /home/maxv/.cargo/registry/src/github.com-1ecc6299db9ec823/lua-src-543.1.0/lua-5.4.3/ldo.c:534: luaD_precall: Assertion `((n) < (L->top - L->ci->func)) && "not enough elements in the stack"' failed.
zsh: abort (core dumped)  RUST_BACKTRACE=full cargo r
```

**Comment by khvzak** [comment] 2021-11-28 17:42
Thanks for the bug report! 
It looks like a bug in mlua. Working on fining a cause/fix.

**Comment by khvzak** [comment] 2021-11-29 10:24
The problem here is worse than I thought. 
`spawn_local` inside the function `my_timer` captures temporary Lua thread (created via `lua.load().exec_async()`) that later GC'ed by Lua and causes panic when trying to access it.
Given that functions has `&Lua` first argument, the `into_static()` hack  lifts lifetimes to `'static` which is simply not safe. It's not even related to async, regular function affected too.

I'm afraid fixing this issue will require quite major API change 😞

**Comment by khvzak** [comment] 2021-12-01 00:48
Alternatively you can rewrite the code to version without `into_static()`:
```rust
    let lua = Rc::new(Lua::new());

    let lua2 = lua.clone();
    lua.globals().set(
        "my_timer",
        lua.create_function(move |lua, (i, f): (u64, LuaFunction)| {
            let f = Rc::new(lua.create_registry_value(f)?);
            let lua2 = lua2.clone();
            tokio::task::spawn_local(async move {
                let dur = std::time::Duration::from_millis(i);
                loop {
                    let lua2 = lua2.clone();
                    let f = f.clone();
                    tokio::task::spawn_local(async move {
                        let f = lua2.registry_value::<LuaFunction>(&f).unwrap();
                        f.call_async::<(), ()>(()).await.unwrap();
                    });
                    tokio::time::sleep(dur).await;
                }
            });
            Ok(())
        })?,
    )?;
```

**Comment by MaxVerevkin** [comment] 2021-12-05 19:16
It works. Kinda messy, but still :)

So, as far as I get it: the lifetime of variables != the lifetime of `Lua` object, because variables may be garbage collected. Right?

**Comment by khvzak** [comment] 2021-12-14 18:29
> So, as far as I get it: the lifetime of variables != the lifetime of Lua object, because variables may be garbage collected. Right?

Roughly, yes. In this case `tokio::task::spawn_local` detaches from a calling function and executes in background capturing scoped variables. It should be solvable but require HRTBs in Rust which is not fully supported.

I'm trying to make an alternative solution.

**Comment by MaxVerevkin** [comment] 2022-03-19 18:44
> It should be solvable but require GATs

When GATs become stable, will it be possible to write the code similar to my original comment, or will the compiler force me to write code like in https://github.com/khvzak/mlua/issues/104#issuecomment-983172209?

**Comment by hackerer1c** [comment] 2022-04-10 01:57
Any update on this issue?

I encountered similar segfault in my own project. However, error messages differ from time to time when I test it:

With `luajit52`:
```
zsh: segmentation fault  cargo run
```

With `lua54`:
```
Assertion failed: ((L->status == 0) && "cannot do calls on non-normal thread"), function lua_pcallk, file lapi.c, line 1055.
zsh: abort      cargo run
```
```
Assertion failed: (((nargs+1) < (L->top - L->ci->func)) && "not enough elements in the stack"), function lua_pcallk, file lapi.c, line 1054.
zsh: abort      cargo run
```
```
hive-server(14235,0x7000063e1000) malloc: Incorrect checksum for freed object 0x7fbe5f029a10: probably modified after being freed.
Corrupt value: 0x600001fcc820
hive-server(14235,0x7000063e1000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      cargo run
```

I am using features `["vendored", "async", "macros", "serialize"]`. My platform is `x86_64-apple-darwin` with Rust 1.58.1.

I am trying to figure out a minimal reproducible code, but my code is a bit complex, so it could be hard to separate the problematic part.

**Comment by khvzak** [comment] 2022-04-10 22:47
Oh, sorry @hackerer1c 
It looks like the `'lua` lifetime is lifted to `'static` and `'callback` lifetime also lifted to `'static` which is not always right.
The main problem there is "context aware" Lua types. It means that, for example a Lua table, can produce different results because of using coroutine-scoped data (if it has metatable attached).
So when you have Lua variables in a callback they all share a context of callback and when moved to outside they continue to use callback data. It's mostly a problem in async context when coroutines are temporary objects.

It's quite complicated issue and I'm currently experimenting with version without `'lua` lifetime and instead use reference counting (eg. if you somehow captured callback data, context would not be destructed).
Also this should simplify many code and lower the mlua entry threshold which is quite high because of "lifetimes hell".

Can you analyze a core dump a get a backtrace? This should help.

---
You could try to enable [this option](https://docs.rs/mlua/latest/mlua/struct.LuaOptions.html#structfield.thread_cache_size) to see how it will change behaviour. But this option would hide the issue rather than solve it.

**Comment by hackerer1c** [comment] 2022-04-11 09:46
> Can you analyze a core dump a get a backtrace? This should help.

[Here they are.](https://gist.github.com/hackerer1c/55e8a4694d92072e2fd4d394f0f1de68)

Core dump backtrace doesn't seem to contain anything related to mlua, only tokio stuff. So I also included the call stack from VS Code (CodeLLDB) when I was debugging (the point when exception occurred).

> You could try to enable [this option](https://docs.rs/mlua/latest/mlua/struct.LuaOptions.html#structfield.thread_cache_size) to see how it will change behaviour. But this option would hide the issue rather than solve it.

I set the the value to 8, and the program continued to run for a few seconds after `assertion failed` occurred.

**Comment by khvzak** [comment] 2022-04-12 10:59
@hackerer1c is there any way for me to reproduce the issue?

**Comment by hackerer1c** [comment] 2022-04-12 13:24
@khvzak If you don't mind, you can use my project to reproduce it. [Here](https://gist.github.com/hackerer1c/64067583ed32da045d4288d0ebb4aed9)'s the instruction.

**Comment by khvzak** [comment] 2022-04-13 14:11
@hackerer1c could you check please the dev branch. I pushed a fix

**Comment by hackerer1c** [comment] 2022-04-14 08:23
@khvzak Fix confirmed. Thanks a lot!

**Comment by khvzak** [comment] 2022-05-27 11:30
I believe it's fixed

**Closed by khvzak** 2022-05-27 11:30 UTC
